general.import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[window.padding]
x = 5
